name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - run: flutter pub get
      - run: flutter build apk

      - name: Rename APK
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/sprintify-$COMMIT_SHA.apk

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/sprintify-*.apk
